In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_excel("/content/uc3m-departamentos-2023-24.xlsx")
df.head()
print(df.shape)
print(df.columns.tolist())

(28, 12)
['curso_academico', 'cod_universidad', 'des_universidad', 'cod_departamento', 'des_departamento', 'cod_municipio', 'des_municipio', 'cod_campus', 'des_campus', 'cod_situacion_departamento', 'des_situacion_departamento', 'fecha_desde_situacion_departamento']

# Remove unnecessary columns

In [2]:
cols_to_drop = [
    "cod_universidad",
    "cod_municipio",
    "cod_situacion_departamento",
    "fecha_desde_situacion_departamento",




]

df = df.drop(columns=cols_to_drop, errors="ignore")
print(df.shape)
df.head()

(28, 8)

,curso_academico,des_universidad,cod_departamento,des_departamento,des_municipio,cod_campus,des_campus,des_situacion_departamento
0,2023-24,Universidad Carlos III de Madrid,55003473,Departamento de Análisis Social,GETAFE,3602,Getafe,Activo
1,2023-24,Universidad Carlos III de Madrid,55001917,Departamento de Biblioteconomía y Documentación,GETAFE,3602,Getafe,Activo
2,2023-24,Universidad Carlos III de Madrid,55004355,Departamento de Ingeniería Aeroespacial,LEGANÉS,3601,Leganés,Activo
3,2023-24,Universidad Carlos III de Madrid,55004354,Departamento de Bioingeniería,LEGANÉS,3601,Leganés,Activo
4,2023-24,Universidad Carlos III de Madrid,55001939,Departamento de Ciencia e Ingeniería de Materi...,LEGANÉS,3601,Leganés,Activo

# Add index

In [3]:
campus_map = {
    "Leganés": 1,
    "Getafe": 2,
    "Colmenarejo": 3,
    "Madrid- Puerta de Toledo": 4,
    "Aranjuez": 5,
    "Intercampus": 6
}

df["cod_campus"] = df["des_campus"].map(campus_map)

df[["des_campus","cod_campus"]].head()

  des_campus  cod_campus
0     Getafe           2
1     Getafe           2
2    Leganés           1
3    Leganés           1
4    Leganés           1

# null values check

In [4]:

null_counts = df.isnull().sum()

print("Null values per column:")
print(null_counts)

Null values per column:
curso_academico               0
des_universidad               0
cod_departamento              0
des_departamento              0
des_municipio                 0
cod_campus                    0
des_campus                    0
des_situacion_departamento    0
dtype: int64

# Department distribution

In [5]:

dept_counts = df["des_departamento"].value_counts()

dept_table = pd.DataFrame({
    "Department": dept_counts.index,
    "Number of Records": dept_counts.values,

})

dept_table

                                           Department  Number of Records
0                     Departamento de Análisis Social                  1
1     Departamento de Biblioteconomía y Documentación                  1
2             Departamento de Ingeniería Aeroespacial                  1
3                       Departamento de Bioingeniería                  1
4   Departamento de Ciencia e Ingeniería de Materi...                  1
5                   Departamento de Ciencias Sociales                  1
6                        Departamento de Comunicación                  1
7   Departamento de Derecho Internacional, Eclesiá...                  1
8   Departamento de Derecho Penal, Procesal e Hist...                  1
9                     Departamento de Derecho Privado                  1
10         Departamento de Derecho Público del Estado                  1
11  Departamento de Derecho Social e Internacional...                  1
12                           Departamento de Economía                  1
13             Departamento de Economía de la Empresa                  1
14                        Departamento de Estadística                  1
15                             Departamento de Física                  1
16  Departamento de Humanidades: Filosofía, Lengua...                  1
17  Departamento de Humanidades: Historia, Geograf...                  1
18                        Departamento de Informática                  1
19  Departamento de Ingeniería de Sistemas y Autom...                  1
20               Departamento de Ingeniería Eléctrica                  1
21                Departamento de Ingeniería Mecánica                  1
22              Departamento de Ingeniería Telemática                  1
23       Departamento de Ingeniería Térmica y Fluidos                  1
24                        Departamento de Matemáticas                  1
25  Departamento de Mecánica de Medios Continuos y...                  1
26             Departamento de Tecnología Electrónica                  1
27  Departamento de Teoría de la Señal y Comunicac...                  1

# Campus distribution

In [6]:

campus_counts = df["des_campus"].value_counts()

campus_table = pd.DataFrame({
    "Campus": campus_counts.index,
    "Number of Departments": campus_counts.values,

})

campus_table

    Campus  Number of Departments
0   Getafe                     14
1  Leganés                     14

# Department per campus distribution

In [ ]:
pd.crosstab(df["des_campus"], df["des_departamento"])

des_departamento,Departamento de Análisis Social,Departamento de Biblioteconomía y Documentación,Departamento de Bioingeniería,Departamento de Ciencia e Ingeniería de Materiales e Ingenieria Química,Departamento de Ciencias Sociales,Departamento de Comunicación,"Departamento de Derecho Internacional, Eclesiástico y Filosofía del Derecho","Departamento de Derecho Penal, Procesal e Historia",Departamento de Derecho Privado,Departamento de Derecho Público del Estado,...,Departamento de Ingeniería Aeroespacial,Departamento de Ingeniería Eléctrica,Departamento de Ingeniería Mecánica,Departamento de Ingeniería Telemática,Departamento de Ingeniería Térmica y Fluidos,Departamento de Ingeniería de Sistemas y Automática,Departamento de Matemáticas,Departamento de Mecánica de Medios Continuos y Teoría de Estructuras,Departamento de Tecnología Electrónica,Departamento de Teoría de la Señal y Comunicaciones
des_campus,,,,,,,,,,,,,,,,,,,,,
Getafe,1,1,0,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
Leganés,0,0,1,1,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

# Save clean dataset

In [7]:

output_path = "departamentos_limpio.xlsx"

df.to_excel(output_path, index=False)

print("File saved as:", output_path)
from google.colab import files
files.download("departamentos_limpio.xlsx")

File saved as: departamentos_limpio.xlsx