# Upload data

In [15]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
departamentos = pd.read_csv("/content/uc3m-departamentos-2023-24.xlsx - Sheet1.csv")

departamentos.head()

,curso_academico,cod_universidad,des_universidad,cod_departamento,des_departamento,cod_municipio,des_municipio,cod_campus,des_campus,cod_situacion_departamento,des_situacion_departamento,fecha_desde_situacion_departamento
0,2023-24,36,Universidad Carlos III de Madrid,55003473,Departamento de Análisis Social,28065,GETAFE,3602,Getafe,1,Activo,20130701
1,2023-24,36,Universidad Carlos III de Madrid,55001917,Departamento de Biblioteconomía y Documentación,28065,GETAFE,3602,Getafe,1,Activo,20130701
2,2023-24,36,Universidad Carlos III de Madrid,55004355,Departamento de Ingeniería Aeroespacial,28074,LEGANÉS,3601,Leganés,1,Activo,20220901
3,2023-24,36,Universidad Carlos III de Madrid,55004354,Departamento de Bioingeniería,28074,LEGANÉS,3601,Leganés,1,Activo,20220901
4,2023-24,36,Universidad Carlos III de Madrid,55001939,Departamento de Ciencia e Ingeniería de Materi...,28074,LEGANÉS,3601,Leganés,1,Activo,20130701

# Inspect structure

In [17]:
print("Shape:", departamentos.shape)

print("\nColumns:")
print(departamentos.columns)

print("\nMissing values:")
print(departamentos.isnull().sum())

Shape: (28, 12)

Columns:
Index(['curso_academico', 'cod_universidad', 'des_universidad',
       'cod_departamento', 'des_departamento', 'cod_municipio',
       'des_municipio', 'cod_campus', 'des_campus',
       'cod_situacion_departamento', 'des_situacion_departamento',
       'fecha_desde_situacion_departamento'],
      dtype='object')

Missing values:
curso_academico                       0
cod_universidad                       0
des_universidad                       0
cod_departamento                      0
des_departamento                      0
cod_municipio                         0
des_municipio                         0
cod_campus                            0
des_campus                            0
cod_situacion_departamento            0
des_situacion_departamento            0
fecha_desde_situacion_departamento    0
dtype: int64

There are no missing values, so no need for imputation or removing rows

In [18]:
departamentos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   curso_academico                     28 non-null     object
 1   cod_universidad                     28 non-null     int64
 2   des_universidad                     28 non-null     object
 3   cod_departamento                    28 non-null     int64
 4   des_departamento                    28 non-null     object
 5   cod_municipio                       28 non-null     int64
 6   des_municipio                       28 non-null     object
 7   cod_campus                          28 non-null     int64
 8   des_campus                          28 non-null     object
 9   cod_situacion_departamento          28 non-null     int64
 10  des_situacion_departamento          28 non-null     object
 11  fecha_desde_situacion_departamento  28 non-null     int64
dtypes: int64(6), object(6)
memory usage: 2.8+ KB

# Standardizing campus identifiers

In [19]:
campus_map = {
    3601: 1,  # Leganés
    3602: 2,  # Getafe
    3603: 3,  # Colmenarejo
    3604: 4,  # Madrid
    3605: 5   # Aranjuez
}

departamentos["campus_id"] = departamentos["cod_campus"].map(campus_map)

departamentos["campus_id"] = departamentos["campus_id"].fillna(6)

departamentos[["cod_campus", "des_campus", "campus_id"]].head()

   cod_campus des_campus  campus_id
0        3602     Getafe          2
1        3602     Getafe          2
2        3601    Leganés          1
3        3601    Leganés          1
4        3601    Leganés          1

# Relevant columns

In [20]:
cols_keep = [
    "cod_departamento",
    "des_departamento",
    "campus_id",
    "des_situacion_departamento",
]

departamentos_clean = departamentos[cols_keep].copy()

departamentos_clean.head()

,cod_departamento,des_departamento,campus_id,des_situacion_departamento
0,55003473,Departamento de Análisis Social,2,Activo
1,55001917,Departamento de Biblioteconomía y Documentación,2,Activo
2,55004355,Departamento de Ingeniería Aeroespacial,1,Activo
3,55004354,Departamento de Bioingeniería,1,Activo
4,55001939,Departamento de Ciencia e Ingeniería de Materi...,1,Activo

# Categorical analysis

### Campus distribution

In [21]:
departamentos["des_campus"].value_counts()

des_campus
Getafe     14
Leganés    14
Name: count, dtype: int64

### Center distribution

In [22]:
departamentos_clean["des_departamento"].value_counts()

des_departamento
Departamento de Análisis Social                                                1
Departamento de Biblioteconomía y Documentación                                1
Departamento de Ingeniería Aeroespacial                                        1
Departamento de Bioingeniería                                                  1
Departamento de Ciencia e Ingeniería de Materiales e Ingenieria Química        1
Departamento de Ciencias Sociales                                              1
Departamento de Comunicación                                                   1
Departamento de Derecho Internacional, Eclesiástico y Filosofía del Derecho    1
Departamento de Derecho Penal, Procesal e Historia                             1
Departamento de Derecho Privado                                                1
Departamento de Derecho Público del Estado                                     1
Departamento de Derecho Social e Internacional Privado                         1
Departamento de Economía                                                       1
Departamento de Economía de la Empresa                                         1
Departamento de Estadística                                                    1
Departamento de Física                                                         1
Departamento de Humanidades: Filosofía, Lenguaje y Literatura                  1
Departamento de Humanidades: Historia, Geografía y Arte                        1
Departamento de Informática                                                    1
Departamento de Ingeniería de Sistemas y Automática                            1
Departamento de Ingeniería Eléctrica                                           1
Departamento de Ingeniería Mecánica                                            1
Departamento de Ingeniería Telemática                                          1
Departamento de Ingeniería Térmica y Fluidos                                   1
Departamento de Matemáticas                                                    1
Departamento de Mecánica de Medios Continuos y Teoría de Estructuras           1
Departamento de Tecnología Electrónica                                         1
Departamento de Teoría de la Señal y Comunicaciones                            1
Name: count, dtype: int64

Usually, we would construct visualisations to easily observe the distribution of campuses and departments. However, since each department appears only once in the dataset, it does not represent a distribution but rather a list of entities. Therefore, visualizations would not provide meaningful additional insights for this dataset. Additionally, there was not much grouped analysis we could conduct, hence that section will be avoided in this notebook.

# Export cleaned dataset

In [23]:
departamentos_clean.to_csv("departamentos.csv", index=False)